AlbumProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views
from . import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")), #redirect to accounts urls file
    url(r"^accounts/", include("django.contrib.auth.urls")), #django package for user authentications
    
    url(r"^albums/",include("albums.urls", namespace="albums")),#redirect to albums urls file
    url(r"^photos/", include("photos.urls", namespace="photos")),#redirect to Photos urls file


    url(r"^$", views.HomePage.as_view(), name="home"),#Homepage : default


    url(r"^test/$", views.TestPage.as_view(), name="test"), # Homepage : after Logging in
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"), # after Logout View


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #for media files: albumCover and photos.

albums/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'albums'

urlpatterns = [
    url(r"^$", views.ListAlbums.as_view(), name="all"), #Album Homepage

    url(r"^new/$", views.CreateAlbum.as_view(), name="create"), # Creating new album
    url(r"^photos/in/(?P<slug>[-\w]+)/$",views.SingleAlbum.as_view(),name="single"), # individual Photos
    url(r"likeAlbum/(?P<slug>[-\w]+)/$",views.LikeAlbum.as_view(),name="like"), #Like Photo
    url(r"unlike/(?P<slug>[-\w]+)/$",views.UnlikeAlbum.as_view(),name="unlike"), #unlike photo
]

photos/urls.py
from django.conf.urls import url

from . import views

app_name='photos'

urlpatterns = [
    #home view for photos
    url(r"^$", views.PhotoList.as_view(), name="all"),
    
    #Posting New  photo
    url(r"new/$", views.CreatePhoto.as_view(), name="create"),
    
    #individual user photo view
    url(r"by/(?P<username>[-\w]+)/$",views.UserPhotos.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PhotoDetail.as_view(),name="single"),
    
    #Delete photo
    url(r"delete/(?P<pk>\d+)/$",views.DeletePhoto.as_view(),name="delete"),
]

albums/models.py
from django.db import models
# Create your models here.

from django.utils.text import slugify
from django.urls import reverse
# Create your models here.
import misaka

from django.contrib.auth import get_user_model

User = get_user_model()

class Album(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    #save album cover to media/albumCover folder
    photo = models.ImageField(upload_to = 'albumCover/',blank=False) 
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    likes = models.ManyToManyField(User,through="AlbumLike")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("albums:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]


class AlbumLike(models.Model):
    album = models.ForeignKey(Album, related_name="likeUnlike",on_delete=models.PROTECT)
    user = models.ForeignKey(User,related_name='user_albums',on_delete=models.PROTECT)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("album", "user")

albums/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from albums.models import Album
from albums.models import AlbumLike
from . import models


#Album creation class
class CreateAlbum(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description","photo")
    model = Album

#single Album view class
class SingleAlbum(generic.DetailView):
    model = Album

#List all album view class 
class ListAlbums(generic.ListView):
    model = Album


#Album Like class 
class LikeAlbum(LoginRequiredMixin, generic.RedirectView):
    
    #refresh the same album after the like
    def get_redirect_url(self, *args, **kwargs):
        return reverse("albums:single",kwargs={"slug": self.kwargs.get("slug")})
    
    #try catch error
    def get(self, request, *args, **kwargs):
        album = get_object_or_404(Album,slug=self.kwargs.get("slug"))

        try:
            AlbumLike.objects.create(user=self.request.user,album=album)

        except IntegrityError:
            messages.warning(self.request,("Warning, already liked  {}".format(album.name)))

        else:
            messages.success(self.request,"Liked {} album.".format(album.name))

        return super().get(request, *args, **kwargs)

#Album UnLike class 
class UnlikeAlbum(LoginRequiredMixin, generic.RedirectView):

    #refresh the same album after the like
    def get_redirect_url(self, *args, **kwargs):
        return reverse("albums:single",kwargs={"slug": self.kwargs.get("slug")})
    
    #try catch error
    def get(self, request, *args, **kwargs):

        try:

            likeUnlike = models.AlbumLike.objects.filter(
                user=self.request.user,
                album__slug=self.kwargs.get("slug")
            ).get()

        except models.AlbumLike.DoesNotExist:
            messages.warning(
                self.request,
                "You can't Unlike this album because you already did."
            )
        else:
           likeUnlike.delete()
           messages.success(
                self.request,
                "You have unliked this album."
            )
        return super().get(request, *args, **kwargs)

albums/templates/albums/album_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block preAlbum %}{% endblock %}
    {% block album_content %}{% endblock %}
    {% block postAlbum %}{% endblock %}
  </div>
</div>

{% endblock %}

albums/templates/albums/album_detail.html
{% extends "albums/album_base.html" %}

{% block preAlbum %}
<div class="text-center">
        <h1>Welcome to <strong>{{album.name}}</strong> Album </h1>
    <img src="{{ album.photo.url }}" class="img-thumbnail" width="250" >
</div>


    <h4> Like Count: {{album.likes.count}}</h4>
    <h3>{{album.name}} album`s photo list: </h3>
    <div class="content">

        {% if user in album.likes.all %}
            <a href="{% url 'albums:unlike' slug=album.slug %}"
            class="btn  btn-fill btn-danger">
            <span class="glyphicon glyphicon glyphicon-thumbs-down"></span> Unlike</a>
        {% else %}
            <a href="{% url 'albums:like' slug=album.slug %}"
            class="btn btn-fill btn-success">
            <span class="glyphicon glyphicon-thumbs-up"></span> Like</a>
        {% endif %}

    </div>
    <br>
{% endblock %}



{% block album_content %}

    <div class="col-md-8">
        {% if album.photos.count == 0 %}
        <h2>No photos in this album yet!</h2>

        {% else %}


            {% for photo in album.photos.all %}
                {% include "photos/_photo.html" %}
            {% endfor %}

        {% endif %}
    </div>

{% endblock %}

albums/templates/albums/album_form.html
{% extends "albums/album_base.html" %}
{% load bootstrap3 %}

{% block album_content %}
<h4>Create A New Album</h4>

  <form method="POST" action="{% url 'albums:create' %}"  enctype="multipart/form-data" id="AlbumForm">
  	{% csrf_token %}
		{% bootstrap_form form %}
		<h5>Upload an album thumbnail here. </h5>
		
		<input type="submit" value="Create" class="btn btn-primary btn-large">
		
  </form>
{% endblock %}

albums/templates/albums/album_list.html
{% extends "albums/album_base.html" %}

{% block preAlbum %}
    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
            <h2>
                Welcome back
                <a href="{% url 'photos:for_user' username=user.username %}">@{{user.username }}</a>
            </h2>

        {% endif %}
                <h2>Albums</h2>

                <p>Welcome to the Albums Page! Select a Album!</p>
        </div>
        {% if user.is_authenticated %}
        <a href="{% url 'albums:create' %}" class="btn btn-md btn-fill btn-warning">
            <span class="glyphicon glyphicon-plus-sign"></span> Create New Album!</a>
        {% endif %}
    </div>
{% endblock %}




{% block album_content %}
	<div class="col-sm-8">
		<div class="item col-xs-5">
		{% for album in object_list %}
		{% if forloop.counter0|divisibleby:3 %} <div class="row text-center">  {%  endif %}

		<div class="card" style="width: 24rem;">
				
			<a class="list-group-item" href="{% url 'albums:single' slug=album.slug %}">
					<h3 class="title list-group-item-heading">{{ album.name }}</h3>
				<div class="card-content">
					{{ album.description_html|safe }} 
					<img class="img-thumbnail"  src="{{ album.photo.url }}" width="180">
					<div class="row">
						<div class="col-md-6">
							<span class="badge">{{ album.likes.count }}</span>like{{ album.likes.count|pluralize }}
						</div>
						<div class="col-md-6">
							<span class="badge">{{ album.photos.count }}</span>photo{{ album.likes.count|pluralize }}
						</div>
					</div>
				</div>
			</a>   
		</div>
		{%  if forloop.counter|divisibleby:3 or forloop.last %}</div><!-- row closing -->{%  endif %}
			{% endfor %}
	</div></div>



{% endblock %}