AlbumProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views
from . import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")), #redirect to accounts urls file
    url(r"^accounts/", include("django.contrib.auth.urls")), #django package for user authentications
    
    url(r"^albums/",include("albums.urls", namespace="albums")),#redirect to albums urls file
    url(r"^photos/", include("photos.urls", namespace="photos")),#redirect to Photos urls file


    url(r"^$", views.HomePage.as_view(), name="home"),#Homepage : default


    url(r"^test/$", views.TestPage.as_view(), name="test"), # Homepage : after Logging in
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"), # after Logout View


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #for media files: albumCover and photos.

albums/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'albums'

urlpatterns = [
    url(r"^$", views.ListAlbums.as_view(), name="all"), #Album Homepage

    url(r"^new/$", views.CreateAlbum.as_view(), name="create"), # Creating new album
    url(r"^photos/in/(?P<slug>[-\w]+)/$",views.SingleAlbum.as_view(),name="single"), # individual Photos
    url(r"likeAlbum/(?P<slug>[-\w]+)/$",views.LikeAlbum.as_view(),name="like"), #Like Photo
    url(r"unlike/(?P<slug>[-\w]+)/$",views.UnlikeAlbum.as_view(),name="unlike"), #unlike photo
]

photos/urls.py
from django.conf.urls import url

from . import views

app_name='photos'

urlpatterns = [
    #home view for photos
    url(r"^$", views.PhotoList.as_view(), name="all"),
    
    #Posting New  photo
    url(r"new/$", views.CreatePhoto.as_view(), name="create"),
    
    #individual user photo view
    url(r"by/(?P<username>[-\w]+)/$",views.UserPhotos.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PhotoDetail.as_view(),name="single"),
    
    #Delete photo
    url(r"delete/(?P<pk>\d+)/$",views.DeletePhoto.as_view(),name="delete"),
]

photos/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models

import misaka

from albums.models import Album

from django.contrib.auth import get_user_model
User = get_user_model()


class Photo(models.Model):
    user = models.ForeignKey(User, related_name="photos",on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now=True)
    photo = models.ImageField(upload_to = 'photos/',blank=False,unique=True) 
    message = models.TextField()
    message_html = models.TextField(editable=False)
    album = models.ForeignKey(Album, related_name="photos",null=True, blank=True,on_delete=models.PROTECT)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "photos:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

photos/forms.py
from django import forms

from photos import models


class PhotoForm(forms.ModelForm):
    class Meta:
        fields = ("message", "album",'photo')
        model = models.Photo

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["album"].queryset = (
                models.Album.objects.filter(
                    pk__in=user.albums.values_list("album__pk")
                )
            )

photos/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms
from . import models 

from django.contrib.auth import get_user_model
User = get_user_model()

#List all photo class
class PhotoList(SelectRelatedMixin, generic.ListView):
    model = models.Photo
    select_related = ("user", "album")

#Individual user photos Class
class UserPhotos(generic.ListView):
    model = models.Photo
    template_name = "photos/user_photo_list.html"

    def get_queryset(self):
        try:
            self.photo_user = User.objects.prefetch_related("photos").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.photo_user.photos.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["photo_user"] = self.photo_user
        return context

#Single photo Detail class 
class PhotoDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Photo
    select_related = ("user", "album")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )

#Posting/Creating a Photo post class
class CreatePhoto(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('message','album','photo')
    model = models.Photo

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs.update({"user": self.request.user})
    #     return kwargs
    
    #form validation
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

#Delete a single Class
class DeletePhoto(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Photo
    select_related = ("user", "album")
    success_url = reverse_lazy("photos:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Photo Deleted")
        return super().delete(*args, **kwargs)

photos/templates/photos/_photo.html
<div class="item col-xs-5">
        <div class="card" style="width: 24rem;">
            
            <div class="card-body">
                <a class="list-group-item" href="{% url 'photos:single' username=photo.user.username pk=photo.pk %}">
                <strong>Uploaded by: {{ photo.user.username }}</strong>
                <h5 align="center">{{ photo.message_html|safe }}</h5>

                <img  class="img-rounded" src="{{ photo.photo.url }}" width="200">
                
                        <a href="{% url 'photos:for_user' username=photo.user.username %}">@{{ photo.user.username }}</a>
                          <time class="time">
                        <a href="{% url 'photos:single' username=photo.user.username pk=photo.pk %}">{{ photo.created_at }}</a></time>
                    
                        {% if photo.album %}
                            <span class="group-name">in <a href="#">{{ photo.album.name }}</a></span>
                        {% endif %}
                
                        {% if user.is_authenticated and photo.user == user and not hide_delete %}
                        <a href="{% url 'photos:delete' pk=photo.pk %}" title="delete" class="btn btn-simple">
                            <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                            <span class="text-danger icon-label">Delete</span>
                        </a>
                    {% endif %}
                </a>
                    </div>
                    </div>
            </div>
   

photos/templates/photos/photo_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
	<div class="container">
		<div class="row">
			{% block prePhoto%}{% endblock %}
			{% block photo_content %}{% endblock %}
			{% block post_photo%}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

photos/templates/photos/photo_confirm_delete.html
{% extends "photos/photo_base.html" %}


{% block photo_content %}

<h3>Are you sure you want to delete this photo?</h3>

<div class="posts">
	{% include "photos/_photo.html" with photo=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'photos:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>

{% endblock %}

photos/templates/photos/photo_detail.html
{% extends "photos/photo_base.html" %}

{% block photo_content %}

<div class="item col-xs-5">
        <div>
            <h3> {{ photo.message_html|safe }} </h3>
            <div>
                <h4>Uploaded by: <strong>{{ photo.user.username }}</strong></h4>
                <img  class="img-rounded" src="{{ photo.photo.url }}" width="800">
                
                        <time class="time"><h5>Photo uploaded at: {{ photo.created_at }}</time></h5>
                    
                        {% if photo.album %}
                            <span class="group-name">in <strong>{{ photo.album.name }}</strong></a></span>
                        {% endif %}
                
                        {% if user.is_authenticated and photo.user == user and not hide_delete %}
                        <a href="{% url 'photos:delete' pk=photo.pk %}" title="delete" class="btn btn-warning">
                            <span class="glyphicon glyphicon-remove " aria-hidden="true"></span>
                            <span>Delete</span>
                        </a>
                    {% endif %}
                </a>
                    </div>
                    </div>
            </div>
   
{% endblock %}

photos/templates/photos/photo_form.html
{% extends "photos/photo_base.html" %}

{% load bootstrap3 %}

{% block photo_content %}

<h4>Post New Photo</h4>
<form method="POST" action="{% url 'photos:create' %}"  enctype="multipart/form-data" id="postForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Post" class="btn btn-primary btn-large">
</form>

{% endblock %}

photos/templates/photos/photo_list.html
{% extends "photos/photo_base.html" %}
{% load humanize %}

{% block pre_photo_content %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Albums</h5>
			<ul class="list-unstyled">
				{# {% get_user_albums as user_albums %}#}
				{% for like_album in get_user_albums %}
				<li class="group li-with-bullet">
					<a href="{% url 'albums:single' slug=like_album.album.slug %}">{{ like_album.album.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
    {% endif %}
    

	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All albums</h5>
			<ul class="list-unstyled">
				{# {% get_other_albums as other_albums %}#}
				{% for other_album in get_other_albums %}
					<li class="group li-with-bullet"><a href="{% url 'albums:single' slug=other_album.slug %}">{{ other_album.name }}</a></li>
				{% endfor %}
			</ul>
			
		</div>
	</div>
</div>

{% endblock %}

{% block photo_content %}
    <div class="col-md-8">
        {% for photo in photo_list %}
        {% include "photos/_photo.html" %}
        {% endfor %}
    </div>
{% endblock %}

photos/templates/photos/user_photo_list.html
{% extends "photos/photo_base.html" %}

{% block prePhoto %}
<div class="col-md-4">
	<h1>@{{ photo_user.username }}</h1>
	<p>Posted Photo History</p>
</div>
{% endblock %}


{% block photo_content %}
<div class="col-md-8">
	{% for photo in photo_list %}
		{% include "photos/_photo.html" %}
	{% endfor %}
</div>
{% endblock %}