AlbumProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views
from . import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")), #redirect to accounts urls file
    url(r"^accounts/", include("django.contrib.auth.urls")), #django package for user authentications
    
    url(r"^albums/",include("albums.urls", namespace="albums")),#redirect to albums urls file
    url(r"^photos/", include("photos.urls", namespace="photos")),#redirect to Photos urls file


    url(r"^$", views.HomePage.as_view(), name="home"),#Homepage : default


    url(r"^test/$", views.TestPage.as_view(), name="test"), # Homepage : after Logging in
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"), # after Logout View


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #for media files: albumCover and photos.

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    #renders login.html from accounts template
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
]

albums/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'albums'

urlpatterns = [
    url(r"^$", views.ListAlbums.as_view(), name="all"), #Album Homepage

    url(r"^new/$", views.CreateAlbum.as_view(), name="create"), # Creating new album
    url(r"^photos/in/(?P<slug>[-\w]+)/$",views.SingleAlbum.as_view(),name="single"), # individual Photos
    url(r"likeAlbum/(?P<slug>[-\w]+)/$",views.LikeAlbum.as_view(),name="like"), #Like Photo
    url(r"unlike/(?P<slug>[-\w]+)/$",views.UnlikeAlbum.as_view(),name="unlike"), #unlike photo
]

photos/urls.py
from django.conf.urls import url

from . import views

app_name='photos'

urlpatterns = [
    #home view for photos
    url(r"^$", views.PhotoList.as_view(), name="all"),
    
    #Posting New  photo
    url(r"new/$", views.CreatePhoto.as_view(), name="create"),
    
    #individual user photo view
    url(r"by/(?P<username>[-\w]+)/$",views.UserPhotos.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PhotoDetail.as_view(),name="single"),
    
    #Delete photo
    url(r"delete/(?P<pk>\d+)/$",views.DeletePhoto.as_view(),name="delete"),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Photo Album </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  </head>

 
  <body>

    <nav class="navbar navbar-dark" style="background-color: #e3f2fd;" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Home</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a href="{% url 'photos:create' %}" class="btn btn-simple">Post photo</a></li>
                      <li><a href="{% url 'albums:all' %}" class="btn btn-simple">Albums</a></li>
                      <li><a href="{% url 'albums:create' %}" class="btn btn-simple">Create Album</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
    						      <li><a href="{% url 'albums:all' %}"class="btn btn-simple">Albums</a></li>
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>

    			</div>
    	</nav>
      
      
      <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



  <canvas id="canvas"></canvas>



  </body>
 
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to the Photo Album !</h1>
  

{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
      <div class="jumbotron">
        <h2>Welcome <a href="{% url 'photos:for_user' username=user.username %}">{{user.username }}</a>!!
        You are now logged in! You Can 
        <a href="{% url 'photos:create' %}">post photos</a> now.
      </h2>


    </div>
</div>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}